name: Export Scarf data
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  export-scarf-data:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: docker://scarf.docker.scarf.sh/scarf-sh/scarf-postgres-exporter:latest
        env:
          SCARF_API_TOKEN: ${{ secrets.SCARF_API_TOKEN }}
          SCARF_ENTITY_NAME: Calcom
          PSQL_CONN_STRING: ${{ secrets.PSQL_CONN_STRING }}
