name: Update Calendso
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch: ~

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Git submodule update
        run: |
          git submodule update --remote --init

      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "actions-user"
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
